### ISSUE TITLE
Arranjos da nova página com dados da Origin.

### ISSUE THREAD

**Issue by venezianluis** [AddressForAll/old-site#11]
**Objetivo**

- [x]  1. Nova página para consumir dados de http://addressforall.org/_sql/origin?limit=1 (_origin_)
- [x]  2. Construir navegabilidade de _origin_ (1) para http://addressforall.org/_sql/donor?limit=1 (_donor_)

**Discussão e observações**
Para montar a nova página _origin_ (1) foi acordado de mostrar o atributo `donor.shortname` invés de `origin.donor_id`, proponho uma view com essa junção, é mais simples que a implementação por PostgREST.

`
select o.*, d.shortname from origin as o left join donor as d on d.donor_id = o.donor_id  
` 
... e caso houver mais colunas para buscar domínio puxar também tudo nessa mesma view, por exemplo no caso do atributo `pack_id`

**Comment by ppKrauss** [comment]
Especificações adicionais:
* na listagem origin o file hash (fhash) precisa ter link para respectivo download, `http://preserv.addressforall.org/download/{fhash}` (vai resultar em um download de extensão `fmeta.ext`).
 
* no lado servidor são tratados como downloads binários normais o `.zip`, e o `.7z`, mas não o gz (GZip). Ver [NGINX/docs/ngx_http_gzip_static_module](http://nginx.org/en/docs/http/ngx_http_gzip_static_module.html), [NGINX/docs/compression](https://docs.nginx.com/nginx/admin-guide/web-server/compression/) e [discussão](https://stackoverflow.com/a/13510477/287948).

**Comment by venezianluis** [comment]
commit 7a7866f38a12bcdb02b4dac9be62fdcd8662a9c7 com novas páginas de origin e donor

**Comment by ppKrauss** [comment]
Sobre o commit 7a7866f38a12bcdb02b4dac9be62fdcd8662a9c7 , que introduziu:
* http://addressforall.org/api-origin
* http://addressforall.org/api-donor

Pequenas falhas:
* o URI Template é `{fhash}.{fmeta.ext}` não `/`
* commits continuam esquecendo de trocar `http://localhost:3001/` pelo site (ex. http://addressforall.org/api-donor?id=25 )
* a busca por Itu não funciona, precisamos pensar em recurso de busca por exato priorizado antes do like.
* ao invés de `ingest_instant` usar `pack_accepted_date`.
* ...

Próximos passos:

1. Para buscar cidades, passar primeiro pelo filtro de estados: http://api.addressforall.org/_sql/vw01states_origin
2. Para buscar doadores de datasets passar primeio pelo filtro de CNPJs:   http://api.addressforall.org/_sql/vw02donors_origin

**Comment by venezianluis** [comment]
commit ce726093920fcf1d6aa12ce1b50ca45d4b9b891e com ajustes, salvo personalização das buscas

**Comment by venezianluis** [comment]
_Documentando_
Redirecionamento de [api-origin](http://addressforall.org/api-origin) para [api-donor](http://addressforall.org/api-donor) está funcionando através do atributo `donor_shortname`.
Para o contrário será desenvolvido através do atributo `legalname`, redirecionando o user para os arquivos que foram doados pelo donor selecionado.

**Comment by ppKrauss** [comment]
API revista em https://github.com/AddressForAll/WS/blob/master/docs/preserv-endpoints.md
e banco de dados sendo revisto para já ficarmos com o definitivo.

**Comment by ppKrauss** [comment]
Mais uma demanda: no final, em HTML estático mesmo, acrescentar

```html
<hr/>
<p>Esta página faz uso dos seguintes <i>endpoints</i>:</p>
...
```

E indicar tabela com endpoint | descrição / link de documentação

**Comment by ppKrauss** [comment]
Lembrete sobre busca global: pode vir a indexação pronta da API, ver https://dba.stackexchange.com/questions/175468/search-all-columns-as-a-single-text-per-row
